# This file was generated by GoReleaser. DO NOT EDIT.
cask "missionctl" do
  postflight_steps do
    on_macos do
      run "/usr/bin/xattr", args: ["-dr", "com.apple.quarantine", "{{staged_path}}/missionctl"]
    end
  end

  version "0.3.1"

  on_macos do
    on_arm do
      sha256 "4260fed2932b486a238ca879911d806c2e0c0cbd82134f9a01b8102813f6a413"
      url "https://github.com/kmarsh/missionctl/releases/download/v#{version}/missionctl_#{version}_darwin_arm64.tar.gz"
    end
    on_intel do
      sha256 "312279b6ed09cf575d233fc7f0f63c1fa15b5907c1add6d487814abadfd587f0"
      url "https://github.com/kmarsh/missionctl/releases/download/v#{version}/missionctl_#{version}_darwin_amd64.tar.gz"
    end
  end
  on_linux do
    on_arm do
      sha256 "039f387d875d389597547a645b18a3bb6b3fec87ef09a23549b653ec654563fb"
      url "https://github.com/kmarsh/missionctl/releases/download/v#{version}/missionctl_#{version}_linux_arm64.tar.gz"
    end
    on_intel do
      sha256 "9c42a3a7b9674976b892d7f3604dfc540f0da969f6f8ef04f7f83f3fe68cbebb"
      url "https://github.com/kmarsh/missionctl/releases/download/v#{version}/missionctl_#{version}_linux_amd64.tar.gz"
    end
  end

  name "missionctl"
  desc "Command-line client for Mission Control projects and time entries"
  homepage "https://github.com/kmarsh/missionctl"

  livecheck do
    skip "Auto-generated on release."
  end

  binary "missionctl"

  # No zap stanza required
end
