# This file was generated by GoReleaser. DO NOT EDIT.
cask "missionctl" do
  version "0.3.0"

  on_macos do
    on_arm do
      sha256 "79ef9edb4842e4c3c22867207e0135a5626dc501738b19058d7f673174ba3455"
      url "https://github.com/kmarsh/missionctl/releases/download/v#{version}/missionctl_#{version}_darwin_arm64.tar.gz"
    end
    on_intel do
      sha256 "127f6342171417198035f863866fc22a7e95abf5e0646459547000399599e2d5"
      url "https://github.com/kmarsh/missionctl/releases/download/v#{version}/missionctl_#{version}_darwin_amd64.tar.gz"
    end
  end
  on_linux do
    on_arm do
      sha256 "cd2ca97a94a4fc9f2ba291bfd1fa3bef44b69bfcbca138edf74150d76c8a9b1f"
      url "https://github.com/kmarsh/missionctl/releases/download/v#{version}/missionctl_#{version}_linux_arm64.tar.gz"
    end
    on_intel do
      sha256 "b3fd1bdbd9979e7b16aeb58996a727209da24d3612bcaf293e356ad35cea3261"
      url "https://github.com/kmarsh/missionctl/releases/download/v#{version}/missionctl_#{version}_linux_amd64.tar.gz"
    end
  end

  name "missionctl"
  desc "Command-line client for Mission Control projects and time entries"
  homepage "https://github.com/kmarsh/missionctl"

  livecheck do
    skip "Auto-generated on release."
  end

  binary "missionctl"

  postflight do
    if OS.mac?
      system_command "/usr/bin/xattr", args: ["-dr", "com.apple.quarantine", "#{staged_path}/missionctl"]
    end
  end

  # No zap stanza required
end
